# Generated by Django 3.1.3 on 2020-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('idlicense', models.AutoField(db_column='idLICENSE', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=10, null=True, unique=True)),
                ('activated', models.DateTimeField(blank=True, db_column='ACTIVATED', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='DURATION', null=True)),
            ],
            options={
                'db_table': 'LICENSE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.IntegerField()),
            ],
        ),
    ]
