# Generated by Django 3.1.3 on 2020-11-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
    ]
