# Generated by Django 3.1.3 on 2020-11-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201128_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='font_size',
        ),
    ]
