# Generated by Django 3.1.3 on 2020-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_snippet_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='snippet',
            name='qty',
            field=models.IntegerField(default=None),
        ),
    ]
