# Generated by Django 3.1.3 on 2020-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201129_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=None)),
                ('duration', models.IntegerField(default=None)),
            ],
        ),
    ]
