# Generated by Django 3.1.3 on 2020-12-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_bulkcreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkCreation',
        ),
    ]
