# Generated by Django 3.1.3 on 2020-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_delete_bulkcreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
